### ISSUE TITLE
Support publicPath and hidden-source-map

### ISSUE THREAD

**Issue by astronomersiva** [ember-cli/broccoli-uglify-sourcemap#125]
webpack supports a variety of options for source maps, which we could bring to the Ember community as well. Two of them that I feel can be useful are:

`publicPath`: The value will be prepended to the value of `sourceMappingURL`. So, for a value of `https://my-vpn/`, the generated `sourceMappingURL` will be, `//# sourceMappingURL=https://my-vpn/app.map`. Implementing this should be as simple as prepending the value of `publicPath` to `url` [here](https://github.com/ember-cli/broccoli-uglify-sourcemap/blob/master/lib/process-file.js#L29).

`hidden-source-map`: Using this option will prevent the reference to the source map from being added to the minified asset. The source maps can be separately uploaded to a private server and then loaded using the "Add Source Map..." option in Chrome. To implement this, we would just have to stop passing the `url` option to terser.

[Further Reading](https://webpack.js.org/configuration/devtool/#production)

**Comment by rwjblue** [comment]
Seems good to me...

**Comment by astronomersiva** [comment]
Raised #126 to address this.

**Comment by astronomersiva** [comment]
@Turbo87, thanks for merging!

Could you also release a new version of ember-cli-uglify? The latest release on the registry v2.1.0 depends on broccoli-uglify-sourcemap@^2.1.1. I see that the PR to update this to v3 was [merged](https://github.com/ember-cli/ember-cli-uglify/pull/93) but hasn't been released yet.

**Comment by Turbo87** [comment]
@astronomersiva thanks for reminding me. I'll release once https://github.com/ember-cli/ember-cli-uglify/pull/102 is merged in as well, to prevent us from having to do yet another major version bump at the end of the month.
