### ISSUE TITLE
Update to terser v4

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/broccoli-uglify-sourcemap#147]
[v4.0.0 of terser has been released](https://github.com/terser-js/terser/blob/master/CHANGELOG.md#v400). It would be nice to see [this PR merged and released](https://github.com/ember-cli/broccoli-uglify-sourcemap/pull/150).

**Comment by boris-petrov** [comment]
@stefanpenner - ping. :)

**Comment by rwjblue** [comment]
https://github.com/ember-cli/broccoli-uglify-sourcemap/releases/tag/v3.2.0
