### ISSUE TITLE
Implement a better way of comparing mapfile output

### ISSUE THREAD

**Issue by blimmer** [ember-cli/broccoli-uglify-sourcemap#19]
The current way [we check](https://github.com/ef4/broccoli-uglify-sourcemap/blob/master/test/test.js#L19) the output of sourcemap files is fragile. It has broken in the past when uglify js changes the output order of their map.

We should implement a solution that is more stable (deep comparison of expected output) to make the tests more tolerant of ordering changes.

**Comment by stefanpenner** [comment]
:+1:
