### ISSUE TITLE
WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.

### ISSUE THREAD

**Issue by pdo-axelor** [ember-cli/broccoli-uglify-sourcemap#228]
Option "nodeWorker" is used: https://github.com/ember-cli/broccoli-uglify-sourcemap/blob/v3.2.0/index.js#L53
Dependency on workerpool 5.+: https://github.com/ember-cli/broccoli-uglify-sourcemap/blob/v3.2.0/package.json#L37

WARNING: Option "nodeWorker" is deprecated since workerpool@5.0.0. Please use "workerType" instead.

**Comment by rwjblue** [comment]
This has been fixed in https://github.com/ember-cli/broccoli-uglify-sourcemap/pull/238 and released in https://github.com/ember-cli/broccoli-uglify-sourcemap/releases/tag/v4.0.0
