### ISSUE TITLE
Update to terser v5

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/broccoli-uglify-sourcemap#235]
[v5.0.0 of terser has been released](https://github.com/terser/terser/blob/master/CHANGELOG.md#v500).

This is important as 1) it's good to use the latest version of the production minifier and 2) nullish coalescing / optional chaining support will only be released in [terser 5](https://github.com/terser/terser/issues/567#issuecomment-667689267) which is needed to fix [this other issue](https://github.com/ember-cli/ember-cli/issues/9290) in `ember-cli`.

**Comment by nickschot** [comment]
Terser 5.2.x with support for optional chaining has been released now.

**Comment by nickschot** [comment]
`terser.minify()` is now async, so some work needs to be done to support it.

https://github.com/ember-cli/broccoli-uglify-sourcemap/blob/master/lib/process-file.js#L51
https://github.com/terser/terser/blob/master/CHANGELOG.md#v500-beta0

**Comment by rwjblue** [comment]
This has been released in https://github.com/ember-cli/broccoli-uglify-sourcemap/releases/tag/v4.0.0
