### ISSUE TITLE
Support for uglify-es

### ISSUE THREAD

**Issue by jboler** [ember-cli/broccoli-uglify-sourcemap#46]
Now that Ember 2.13 has babel browser targeting, the build can contain ES6 code which uglify-js doesn't support. I've been using babili but it takes twice as long and produces larger files than uglify-es.

Someone has already made a branch for this but an official ember-cli packages would be great.

https://github.com/fusion2004/broccoli-uglify-es-sourcemap
https://github.com/fusion2004/ember-cli-uglify-es

**Comment by rwjblue** [comment]
Yep, I asked @fusion2004 to submit patches here.  Would love to update the main project.

**Comment by fusion2004** [comment]
I will hopefully be getting to that very soon! Sorry I haven't gotten to it sooner.

**Comment by rwjblue** [comment]
Sweet!

**Comment by Turbo87** [comment]
Resolved by https://github.com/ember-cli/broccoli-uglify-sourcemap/pull/47
