### ISSUE TITLE
Switch from uglify-es to terser

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/broccoli-uglify-sourcemap#68]
`uglify-es` [has been unmaintained](https://github.com/mishoo/UglifyJS2/issues/3010#issuecomment-374018994) for quite a while now. I've been following [terser](https://github.com/fabiosantoscode/terser) for a while now and it has now been officially renamed to that and has an official package in `npm`. It is continued by two of the biggest contributors of `uglify-es`. I suggest using `terser` instead of `uglify-es` from now on. And a new release including it would be nice. :)

**Comment by stefanpenner** [comment]
https://github.com/ember-cli/broccoli-uglify-sourcemap/issues/69
