### ISSUE TITLE
 New dependency name: uglify-es => terser #1 

### ISSUE THREAD

**Issue by fabiosantoscode** [ember-cli/broccoli-uglify-sourcemap#69]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by boris-petrov** [comment]
I actually managed to create [another issue](https://github.com/ember-cli/broccoli-uglify-sourcemap/issues/68) a couple of minutes before you. :) @stefanpenner, @mikrostew - ping. :)

**Comment by stefanpenner** [comment]
@boris-petrov / @fabiosantoscode nice, thanks for letting us know. I'm fine with making this change, assuming we know what the differences are and if a minor/major bump is required.

If either of you have time to do ^ and report back, I can quickly release based on your findings.

**Comment by stefanpenner** [comment]
It claims compat: https://github.com/fabiosantoscode/terser#note

**Comment by stefanpenner** [comment]
cc @Turbo87 / @rwjblue

**Comment by Turbo87** [comment]
why was this forked?

**Comment by stefanpenner** [comment]
🤷‍♂️

**Comment by Turbo87** [comment]
@stefanpenner for future reference: https://github.com/fabiosantoscode/terser/issues/2

**Comment by Turbo87** [comment]
hmm, I'm wondering if we should fork this and make a `broccoli-terser` package instead of integrating it here. keeping the uglify name while using something else underneath might be confusing 🤔

**Comment by stefanpenner** [comment]
> @stefanpenner for future reference: fabiosantoscode/terser#2

Thanks, so it seems like its just the new version? Why not just major bump....

**Comment by Turbo87** [comment]
@stefanpenner we discussed this in the call yesterday. the plan is to update this package to use `terser` for now and if we are confident that the dust has settled and `terser` is indeed the new thing to use we will rename it to `broccoli-terser`.
